# Generated by Django 4.0.5 on 2022-06-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.ManyToManyField(to='api.title'),
        ),
    ]
