# Generated by Django 4.0.5 on 2022-06-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tag_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='title',
        ),
        migrations.AddField(
            model_name='title',
            name='tags',
            field=models.ManyToManyField(to='api.tag'),
        ),
    ]
