# Generated by Django 4.0.5 on 2022-07-11 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_tag_title_title_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='total_click',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Like Count'),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='api.title'),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='title',
            name='tags',
            field=models.ManyToManyField(related_name='tag', to='api.tag'),
        ),
    ]
