# Generated by Django 4.0.5 on 2022-07-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_title_total_click_alter_explanation_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='beginner', max_length=40),
        ),
    ]
