# Generated by Django 4.0.5 on 2022-07-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('BG', 'Beginner'), ('MD', 'Middle'), ('PR', 'Proffessional')], default='BG', max_length=2),
        ),
    ]
