# Generated by Django 4.0.5 on 2022-07-27 12:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_blog_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanation',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
